"""Skill sync: regenerates the bundled skills from the maintainer's local skills directory (ADR 0001).

The plugin directory is generated whole on every sync, so a refresh is a plain
overwrite that the maintainer reviews as a diff; nothing in it is edited by hand.
"""

import json
import os
import re
import shutil
import tempfile
from typing import Optional

from ralph.errors import RalphError

BUNDLED = ("implement", "tdd", "code-review", "to-tickets")
PLUGIN_NAME = "ralph"
LICENSE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "upstream-skills-license.txt")

README = """\
# Ralph's bundled skills

Generated by `ralph sync-skills` from the maintainer's local skills; never edit anything in this directory by hand.
Refresh it with that command and review the result as a diff.
Anything that must differ for unattended use belongs in ralph's prompts (docs/adr/0001).

The skills are invoked as `ralph:<name>` and are covered by the upstream license notice in LICENSE.

## Origins

"""


def sync(source: str, plugin: str) -> list:
    """Replaces `plugin` with a plugin bundling the skills found in `source`.

    `source` is recorded as given (so `~` stays `~`). Returns the references
    to skills in `source` that are not bundled, as `(path within skills/,
    reference)` pairs.
    """
    directory = os.path.expanduser(source)
    missing = [name for name in BUNDLED if not os.path.isfile(os.path.join(directory, name, "SKILL.md"))]
    if missing:
        raise RalphError(f"cannot sync, {source} has no skill named: " + ", ".join(missing))

    unbundled = _reference(set(_skills(directory)) - set(BUNDLED))
    found = []
    origins = []
    build = tempfile.mkdtemp(prefix=".plugin-", dir=os.path.dirname(os.path.abspath(plugin)))
    try:
        _write(
            os.path.join(build, ".claude-plugin", "plugin.json"),
            json.dumps({"name": PLUGIN_NAME, "description": "Ralph's bundled skills."}, indent=2) + "\n",
        )
        _write(os.path.join(build, "LICENSE"), _read(LICENSE))
        for name in BUNDLED:
            original = os.path.realpath(os.path.join(directory, name))
            copy = os.path.join(build, "skills", name)
            shutil.copytree(original, copy)
            for path in _markdown(copy):
                text = _read(path)
                where = os.path.relpath(path, os.path.join(build, "skills"))
                found += [(where, r) for r in sorted({_named(m) for m in unbundled.finditer(text)})]
                _write(path, _repoint(text))
            origins.append(_origin(name, os.path.join(source, name), _upstream(original, name)))
        _write(os.path.join(build, "README.md"), README + "".join(origins))
        if os.path.exists(plugin):
            shutil.rmtree(plugin)
        os.rename(build, plugin)
        return sorted(found)
    except BaseException:
        shutil.rmtree(build, ignore_errors=True)
        raise


def _origin(name: str, copied_from: str, upstream: Optional[dict]) -> str:
    line = f"- `{name}`: copied from `{copied_from}`, "
    if not upstream:
        return line + "no upstream recorded\n"
    path = os.path.dirname(upstream.get("skillPath", "")) or "."
    return line + f"upstream {upstream.get('sourceUrl')} `{path}` at `{upstream.get('skillFolderHash')}`\n"


def _upstream(original: str, name: str) -> Optional[dict]:
    """The upstream of an installed skill, from the lock file the skills installer keeps beside its skills directory."""
    lock = os.path.join(os.path.dirname(os.path.dirname(original)), ".skill-lock.json")
    try:
        with open(lock) as f:
            return json.load(f).get("skills", {}).get(name)
    except (OSError, ValueError):
        return None


def _reference(names) -> "re.Pattern[str]":
    """Matches a reference to one of the named skills: `/name`, or the bare name in backticks or quotes.

    Group "slash" or "quoted" holds the name. Paths such as `skills/tdd/` and
    words in prose are not references.
    """
    if not names:
        return re.compile(r"(?!)")
    alternatives = "|".join(re.escape(n) for n in sorted(names, key=len, reverse=True))
    return re.compile(
        rf"(?<![\w/.:-])/(?P<slash>{alternatives})(?![\w/:-])|(?P<q>[`\"'])(?P<quoted>{alternatives})(?P=q)"
    )


def _named(match: "re.Match[str]") -> str:
    return "/" + match.group("slash") if match.group("slash") else match.group("quoted")


def _repoint(text: str) -> str:
    def namespaced(match: "re.Match[str]") -> str:
        if match.group("slash"):
            return f"/{PLUGIN_NAME}:{match.group('slash')}"
        quote = match.group("q")
        return f"{quote}{PLUGIN_NAME}:{match.group('quoted')}{quote}"

    return _reference(BUNDLED).sub(namespaced, text)


def _skills(directory: str) -> list:
    return [n for n in os.listdir(directory) if os.path.isfile(os.path.join(directory, n, "SKILL.md"))]


def _markdown(directory: str) -> list:
    found = []
    for parent, _, names in os.walk(directory):
        found += [os.path.join(parent, n) for n in names if n.endswith(".md")]
    return sorted(found)


def _read(path: str) -> str:
    with open(path) as f:
        return f.read()


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
